### ISSUE TITLE
Add option for only flattening nested maps, not arrays

### ISSUE THREAD

**Issue by alexwennerberg** [durch/rust-flatten-json#1]
Hi! Not sure if this library is being maintained, but I'm using it for https://github.com/alexwennerberg/json2csv (currently a WIP). I think something that would be valuable would be an option to only flatten nested maps, but not flatten arrays, or to only flatten nested arrays, but not nested maps. I may submit a pull request!

**Comment by durch** [comment]
Hi @alexwennerberg, I honestly forgot I built this :). I'll start maintaining it now. Would be happy to take a PR!

**Comment by alexwennerberg** [comment]
I put together a PR but realized that it is not necessary for my use case, so I closed it. I'll be keeping an eye on this repo though during development
